version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    expose:
      - "5432"
    env_file:
      - ./movies_admin/.env
    volumes:
      - /postgresql/data:/var/lib/postgresql/data
      
  django:
    build: movies_admin
    container_name: django
    expose:
      - "8000"
    env_file:
      - ./movies_admin/.env
    volumes:
      - ./movies_admin/staticfiles:/static:ro
      - ./movies_admin/run_uwsgi.sh:/run_uwsgi.sh
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./movies_admin/src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./movies_admin/src/configs:/etc/nginx/conf.d:ro
      - ./movies_admin/staticfiles:/static:ro
    depends_on:
      - django
