# Generated by Django 4.2.5 on 2023-12-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmwork',
            options={'verbose_name': 'filmwork', 'verbose_name_plural': 'filmworks'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='genrefilmwork',
            options={'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
        migrations.AlterModelOptions(
            name='personfilmwork',
            options={'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
        migrations.RenameField(
            model_name='filmwork',
            old_name='persones',
            new_name='persons',
        ),
        migrations.AddField(
            model_name='filmwork',
            name='type_choice',
            field=models.CharField(choices=[('MV', 'movie'), ('TS', 'tv show')], default='MV', max_length=2, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(max_length=255, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[('ACT', 'actor'), ('DIR', 'director'), ('WRT', 'writer')], max_length=3, verbose_name='role'),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['creation_date', 'rating'], name='creation_date_rating'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['full_name'], name='full_name_person'),
        ),
        migrations.AddIndex(
            model_name='personfilmwork',
            index=models.Index(fields=['film_work', 'person'], name='film_work_person_idx'),
        ),
        migrations.AddConstraint(
            model_name='genrefilmwork',
            constraint=models.UniqueConstraint(fields=('film_work', 'genre'), name='film_work_genre_idx'),
        ),
    ]
